Models/ErrorViewModel.cs
namespace Projeto_aplicação_para_emprestimos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/emprestimosmodel.cs
namespace Projeto_aplicação_para_emprestimos.Models
{
    public class Emprestimosmodel
    {
        public int Id { get; set; }
        public required string Recebedor { get; set; }
        public required string Fornecedor { get; set; }
        public required string Livro { get; set; }
        public DateTime DataUtimautilizacao  { get; set; } = DateTime.Now;



    }
}

Controllers/EmprestimoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using Projeto_aplicação_para_emprestimos.Data;
using Projeto_aplicação_para_emprestimos.Models;
using System.Collections.Generic;

namespace Projeto_aplicação_para_emprestimos.Controllers
{
    public class EmprestimoController : Controller
    {
        readonly private ApplicationDbContext _db;
        public EmprestimoController(ApplicationDbContext db)
        {
            _db = db;
        }

        public int EmprestimosModel { get; private set; }

        public IActionResult Index()
        {
            IEnumerable<Emprestimosmodel> emprestimos = _db.Emprestimos;

            return View(emprestimos);
        }
    }

    
 }

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Projeto_aplicação_para_emprestimos.Models;

namespace Projeto_aplicação_para_emprestimos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Emprestimo/Index.cshtml
@model IEnumerable<Emprestimosmodel>

<table class="table table-dark table-hover">
    <thead>
        <tr>
            <th scope="col">Recebedor</th>
            <th scope="col">Fornecedor</th>
            <th scope="col">Livro</th>
            <th scope="col">Útima Atualização</th>
        </tr>
    </thead>
    <tbody>

        @if(Model!=null)
        {
			@foreach (var emprestimo in Model)
			{
                <tr>


                    <th scope="row">@emprestimo.Recebedor</th>
                    <td>@emprestimo.Fornecedor</td>
                    <td>@emprestimo.Livro</td>
                    <td>@emprestimo.DataUtimautilizacao</td>
                </tr>
			}
           
        }
      
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_aplicação_para_emprestimos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projeto_aplicação_para_emprestimos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto_aplicação_para_emprestimos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Projeto_aplicação_para_emprestimos - <a asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimos</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>